import * as dotenv from 'dotenv';
dotenv.config();

import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import * as schema from './schema';
import { eq } from 'drizzle-orm';
import { subHours, subDays } from 'date-fns';

async function main() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL! });
  const db = drizzle(pool, { schema });

  const users = await db.select({ id: schema.user.id, email: schema.user.email }).from(schema.user);

  if (!users.length) {
    console.log('Nenhum usuário encontrado.');
    await pool.end();
    return;
  }

  const user = users[2];
  console.log(`Inserindo notificações para: ${user.email}`);

  await db.delete(schema.notification).where(eq(schema.notification.userId, user.id));

  const now = new Date();

  await db.insert(schema.notification).values([
    {
      userId: user.id,
      type: 'goalAchieved',
      title: 'Meta atingida!',
      body: 'Você atingiu 100% da meta "Viagem para Europa".',
      read: false,
      createdAt: subHours(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Reserva de emergência" vence em breve',
      body: 'Faltam R$ 1.200,00 para atingir sua meta. Prazo: 28 de março de 2026.',
      read: false,
      createdAt: subHours(now, 3),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
     {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Aluguel de R$ 1.800,00 foi executado em 21/03/2026.',
      read: false,
      createdAt: subHours(now, 6),
    },
    {
      userId: user.id,
      type: 'transferCreated',
      title: 'Transferência realizada',
      body: 'R$ 500,00 de Nubank → Inter em 21/03/2026.',
      read: true,
      createdAt: subDays(now, 1),
    },
    {
      userId: user.id,
      type: 'goalDeadline',
      title: 'Meta "Notebook novo" vence em breve',
      body: 'Faltam R$ 300,00 para atingir sua meta. Prazo: 25 de março de 2026.',
      read: true,
      createdAt: subDays(now, 2),
    },
    {
      userId: user.id,
      type: 'scheduledReminder',
      title: 'Transação agendada executada',
      body: 'Spotify de R$ 21,90 foi executado em 19/03/2026.',
      read: true,
      createdAt: subDays(now, 3),
    },
  ]);

  console.log('✓ 6 notificações inseridas (3 não lidas, 3 lidas).');
  await pool.end();
}

main().catch((e) => { console.error(e); process.exit(1); });
